"=============================================================================
"     FileName: _vimrc
"         Desc: 
"       Author: loseblue
"        Email: loseblue[a]163.com
"      Version: 0.0.1
"   LastChange: 2012-08-03 10:45:45
"      History:
"=============================================================================
" Platform
function! MySys()
  if has('win32') || has('win64')
    return "windows"
  else
    return "linux"
  endif
endfunction

"=========================== Vundle start ================================
set nocompatible    " be iMproved
filetype off        " required!

if MySys() == 'windows'
	set rtp+=~/.vim/bundle/vundle/
else
	set rtp+=~/.vim/bundle/vundle/
endif

call vundle#rc()
" required!
Bundle 'gmarik/vundle'

" vim-scripts repos
Bundle 'a.vim'
Bundle 'cocoa.vim'
Bundle 'loseblue/AuthorInfo'
Bundle 'EasyMotion'
Bundle 'Mark'
Bundle 'matchit.zip'
Bundle 'gmarik/snipmate.vim'
Bundle 'The-NERD-Commenter'
Bundle 'project.tar.gz'
Bundle 'loseblue/springColorScheme'
Bundle 'Tagbar'
Bundle 'taglist.vim'
Bundle 'TeTrIs.vim'
Bundle 'loseblue/trcBrowser'
Bundle 'TxtBrowser'
Bundle 'winmanager--Fox'

filetype plugin indent on    " required!
colorscheme spring  " color scheme 
"=========================== END Vundle ================================


set nobackup      " cloese backup
syntax enable       " 
set display=lastline
filetype on " detect file type
filetype plugin on " detect file type
filetype indent on " detect file type
set iskeyword+=_,$,@,%,#,-

set backspace=2     " backspace can be used
set nu!             " show line number
set autoread        " Set to auto read when a file is changed from the outside
set foldenable
set fdm=indent      " floader lines
nnoremap <space> @=((foldclosed(line('.')) < 0) ? 'zc' : 'zo')<CR>
"set showcmd "shwo cursor poistion in nomoal mode 
set cursorcolumn  " high light cursor column
set cursorline    " high light cursor line
set linespace=0   " set line high space
set lines=20 columns=110 "init UI size
set linebreak      "Do not cut words between lines, USELESS!
" set foldmethod=marker
" let g:showmarks_marks = 'abcdefghijklmnopqrstuvwxyz'  " set bookMark

"assigned line setting 
set list
set listchars=tab:\|-
set tabpagemax=15 
set showtabline=2

set paste
nmap <silent> <A-q> :q<CR>

" shut down error ringBell
set noerrorbells
set novisualbell
set t_vb=

"window jump in VIM Ctrl + hjkl
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" status line setting [including OS,filecoding, course position,present, time]
"set statusline=[FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]\ %y%r%m%*%=\ %{strftime(\"%d/%m/%y\ -\ %H:%M\")}


" file encoding setting
set fileencodings=utf-8,chinese,latin-1
if has("win32")
"set fileencoding=chinese
set fileencoding=utf-8
else
set fileencoding=utf-8
endif

" C setting
set sm              " OMG
set tabstop=4       " set width of tab
set softtabstop=4
set shiftwidth=4    " set with of assignment blank num = 4
set autoindent      "auto indent
set cindent         

"Set mapleader
let mapleader = ","
let g:mapleader = ","
set ignorecase smartcase "search cease smart


" VIM font setting
" 17~19£¨or more£©
set guifont=yaheiInconsolata:h10.5:cANSI
"set gfw=Yahei_Mono:h10.5:cGB2312
" 12£¨or less£©~14
"set gfw=Yahei_Mono:h9:cGB2312
"set gfw=Yahei_Mono:h10:cGB231

" Ctrl+S
imap <C-s> <Esc>:wa!<cr>i<Right>
nmap <C-s> :wa!<cr>
set nocompatible
"source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

"ctrl+c ctrl+v ctrl+x
:map <C-V> "+pa
:map <C-C> "+y
:map <C-X> "+x

" file code type
set ffs=dos,unix
nmap <leader>fd :se ff=dos<cr>
nmap <leader>fu :se ff=unix<cr>

" copy current file/path to clipboard ,p:file name & path ,P:only path
noremap ,p :let @*=expand("%:p")<CR><Esc>
noremap ,P :let @*=expand("%:p:h")<CR><Esc>

"To hex modle
let s:hexModle = "N"
function! ToHexModle()
  if s:hexModle == "Y"
    %!xxd -r
    let s:hexModle = "N"
  else
    %!xxd
    let s:hexModle = "Y"
  endif
endfunction


" """"""""""""""""""" F1-F12"""""""""""""""""""""""""
" F1 Toggle Menu and Toolbar
set guioptions-=m
set guioptions-=T
set guioptions-=l
"set guioptions-=r
map <silent> <F1> :if &guioptions =~# 'T' <Bar>
		\set guioptions-=T <Bar>
        \set guioptions-=m <bar>
        \set guioptions-=l <bar>
        "\set guioptions-=r <bar>
    \else <Bar>
		\set guioptions+=T <Bar>
        \set guioptions+=m <Bar>
        \set guioptions+=l <Bar>
        "\set guioptions+=r <Bar>
    \endif<CR>

"F2 show files used open
map <F2> :MRU<cr>

"F4 file infor
let g:vimrc_author='loseblue' 
let g:vimrc_email='loseblue[a]163.com' 
let g:vimrc_homepage='http://www.google.com' 
nmap <F4> :AuthorInfoDetect<cr>

"F5 use python
map <F5> :!python.exe %<CR>
"F6 change to Hex mode
map <F6> :call ToHexModle()<cr>
"F7 insert time
imap <F7> <C-R>=strftime("%c")<CR>

" <F9> open Tagbar
nmap <silent> <F9> :TagbarToggle<CR>
nmap <silent> <C-F9> :Tlist<CR>
let tags=$VIM . "\\soft\\ctags.exe"
let g:tagbar_left = 1
let g:tagbar_singleclick = 0
let g:tagbar_ctags_bin = 'ctags'
let g:tagbar_width = 30

" roll screen Alt + jk
noremap <A-j> <C-f>
noremap <A-k> <C-b>


" winManger setting

let g:Tagbar_title="[Tagbar]"
let g:Project_title="[Project]"
"let g:winManagerWindowLayout="Tagbar|Project"
let g:winManagerWindowLayout="TagList|FileExplorer"

function! Tagbar_Start()
	exec 'TagbarToggle'
endfunction
function! Tagbar_IsValid()
	return 1
endfunction
function! Project_Start()
	exec 'Project'
endfunction
function! Project_IsValid()
	return 1
endfunction

nmap wm :WMToggle<cr>


"au BufRead,BufNewFile *  setfiletype txt
"au BufRead,BufNewFile *  setfiletype trc
au BufEnter,BufRead,BufNewFile *.txt setlocal ft=txt "txtBrowser called
au BufEnter,BufRead,BufNewFile *.trc setlocal ft=trc "trcBrowser called
